### ISSUE TITLE
APIJSONDemo-Druid 无法从DemoDataSourceConfig获取数据库连接

### ISSUE THREAD

**Issue by SLD-Allen** [Tencent/APIJSON#303]
**环境信息**
 - 系统: Windows 10
 - JDK: 1.8.0_17
 - 数据库: MySQL 5.7.14
 - APIJSON:  2.9.1

**问题描述**
1. 直接获取APIJSONDemo-Druid 工程代码
2. 修改application.yml中数据库信息
3. 项目启动报错，无法获取数据源
4. 在DemoSQLConfig文件中添加getDBUri/getDBAccount/getDBPassword方法，配置数据库信息【按注释应该不需要配置】
5. 项目启动成功

**错误信息**
2021-08-22 14:39:27.467  INFO 7028 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2021-08-22 02:39:27.470: AbstractSQLExecutor.INFO: select  connection  = null
2021-08-22 02:39:27.470: DemoSQLExecutor.DEBUG: ds.getConnection() = com.mysql.cj.jdbc.ConnectionImpl@37864b77
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at apijson.orm.AbstractSQLExecutor.getConnection(AbstractSQLExecutor.java:740)
	at apijson.demo.DemoSQLExecutor.getConnection(DemoSQLExecutor.java:57)
	at apijson.orm.AbstractSQLExecutor.getStatement(AbstractSQLExecutor.java:705)
	at apijson.orm.AbstractSQLExecutor.executeQuery(AbstractSQLExecutor.java:838)
	at apijson.orm.AbstractSQLExecutor.execute(AbstractSQLExecutor.java:233)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:1614)
	at apijson.orm.AbstractObjectParser.onSQLExecute(AbstractObjectParser.java:845)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:713)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:903)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:517)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:256)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:839)
	at apijson.orm.AbstractParser.onArrayParse(AbstractParser.java:1029)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:497)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:256)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:839)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:398)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:115)
	at apijson.framework.APIJSONVerifier.initAccess(APIJSONVerifier.java:164)
	at apijson.framework.APIJSONVerifier.initAccess(APIJSONVerifier.java:135)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:78)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at apijson.demo.DemoApplication.main(DemoApplication.java:69)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 31 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 34 more
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

**Comment by SLD-Allen** [comment]
DemoSQLExecutor 修改修改代码
@Override
	public Connection getConnection(SQLConfig config) throws Exception {
	    Log.d(TAG, "getConnection  config.getDatasource() = " + config.getDatasource());
		
		Connection c = connectionMap.get(config.getDatabase());
		if (c == null || c.isClosed()) {
			try {
				DemoDataSourceConfig ds = DemoApplication.getApplicationContext().getBean(DemoDataSourceConfig.class);
				connectionMap.put(config.getDatabase(), ds == null ? null : ds.druidDataSource().getConnection());
			} catch (Exception e) {
				Log.e(TAG, "getConnection   try { "
						+ "DataSource ds = DemoApplication.getApplicationContext().getBean(DataSource.class); .."
						+ "} catch (Exception e) = " + e.getMessage());
			}
		}

		// 必须最后执行 super 方法，因为里面还有事务相关处理。
		// 如果这里是 return c，则会导致 增删改 多个对象时只有第一个会 commit，即只有第一个对象成功插入数据库表
		return super.getConnection(config);
	}

**Comment by SLD-Allen** [comment]
直接下载的代码：
@Override
	public Connection getConnection(SQLConfig config) throws Exception {
	    //		Log.d(TAG, "getConnection  config.getDatasource() = " + config.getDatasource());
		
		Connection c = connectionMap.get(config.getDatabase());
		if (c == null || c.isClosed()) {
			try {
				DataSource ds = DemoApplication.getApplicationContext().getBean(DataSource.class);
				// 另一种方式是 DruidConfig 初始化获取到 Datasource 后给静态变量 DATA_SOURCE 赋值： ds = DruidConfig.DATA_SOURCE.getConnection();
				connectionMap.put(config.getDatabase(), ds == null ? null : ds.getConnection());
			} catch (Exception e) {
				Log.e(TAG, "getConnection   try { "
						+ "DataSource ds = DemoApplication.getApplicationContext().getBean(DataSource.class); .."
						+ "} catch (Exception e) = " + e.getMessage());
			}
		}

		// 必须最后执行 super 方法，因为里面还有事务相关处理。
		// 如果这里是 return c，则会导致 增删改 多个对象时只有第一个会 commit，即只有第一个对象成功插入数据库表
		return super.getConnection(config);
	}

**Comment by TommyLemon** [comment]
可能是数据库连接数满了，设置下全局最大连接数，然后重启数据库和服务试试

**Comment by SLD-Allen** [comment]
> 可能是数据库连接数满了，设置下全局最大连接数（改成比原来大的值），然后重启数据库和服务试试

![image](https://user-images.githubusercontent.com/89327023/130551724-191fbc63-1548-414e-ae34-defe5c79df20.png)
最后返回的是 super.getConnection(config);从SQLConfig获取连接，那么DemoDataSourceConfig配置的数据源是不是就没有获取

**Comment by TommyLemon** [comment]
> > 可能是数据库连接数满了，设置下全局最大连接数（改成比原来大的值），然后重启数据库和服务试试
> 
> ![image](https://user-images.githubusercontent.com/89327023/130551724-191fbc63-1548-414e-ae34-defe5c79df20.png)
> 最后返回的是 super.getConnection(config);从SQLConfig获取连接，那么DemoDataSourceConfig配置的数据源是不是就没有获取

问题应该是同事贡献代码改了 key，从 config.getDatabase() 改为 config.getDatabase() + "-" + config.getDatasource() 
https://github.com/Tencent/APIJSON/pull/262/commits/cd83f506f2bc415a4c8c1292ef6dde37dd13a046

我这边没有同步修改 demo，你在以上代码里也这样改下试试

**Comment by SLD-Allen** [comment]
![image](https://user-images.githubusercontent.com/89327023/130598961-1fde3f87-70f7-4bfb-9951-a81ce81b6e83.png)
还是不行唉@TommyLemon

**Comment by TommyLemon** [comment]
> ![image](https://user-images.githubusercontent.com/89327023/130598961-1fde3f87-70f7-4bfb-9951-a81ce81b6e83.png)
> 还是不行唉@TommyLemon

你只改了 get 没改 put

**Comment by TommyLemon** [comment]
@SLD-Allen 现在可以了吗？

**Comment by SLD-Allen** [comment]
> @SLD-Allen 现在可以了吗？

可以了，感谢您的解答
