### ISSUE TITLE
循环调用GET请求，出现超出 ORA-00604: 递归 SQL 级别 1 出现错误 ORA-01000: 超出打开游标的最大数

### ISSUE THREAD

**Issue by liuliangxing** [Tencent/APIJSON#312]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

动态从200张表里查询数据，所以使用循环调用GET 请求，然后就出现了：超出 ORA-00604: 递归 SQL 级别 1 出现错误 ORA-01000: 超出打开游标的最大数，有什么解决思路嘛，还望大佬指点一二。

**错误信息**

java.sql.SQLException: ORA-00604: 递归 SQL 级别 1 出现错误
ORA-01000: 超出打开游标的最大数
ORA-00604: 递归 SQL 级别 1 出现错误
ORA-01000: 超出打开游标的最大数
ORA-00604: 递归 SQL 级别 1 出现错误
ORA-01000: 超出打开游标的最大数

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3628)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1493)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at apijson.orm.AbstractSQLExecutor.executeQuery(AbstractSQLExecutor.java:837)
	at apijson.orm.AbstractSQLExecutor.execute(AbstractSQLExecutor.java:233)

**Comment by TommyLemon** [comment]
数据库设置最大连接数

**Comment by liuliangxing** [comment]
> 数据库设置最大连接数。另外你这么做目的是什么？

根据页面输入的模型生成对应的表，然后利用apijson 动态的去增删改查这些动态表。正常操作都没有问题，就是有一个全量导出数据，随着动态表的数量增加，就会出现这个问题。
