### ISSUE TITLE
Cannot invoke "java.lang.Boolean.booleanValue()" 

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#642]
### APIJSON Version/APIJSON 版本号

6.2.0

### Database Type & Version/数据库类型及版本号

mysql

### Environment/环境信息

```markdown
**环境信息**  
 系统: Windows 11 10.0 
 数据库: <!-- 请填写，例如 MySQL 5.7。默认数据库为 MYSQL --> 
 JDK: 21.0.1 amd64 
 APIJSON: 6.2.0
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

程序无法正常运行

### Current Behavior/问题描述

```markdown
**问题描述**
Cannot invoke "java.lang.Boolean.booleanValue()" 

access 表添加了字段  deletedKey  deletedValue notDeletedValue

重写了

   @Override
    public boolean isFakeDelete() {
        return true;
    }

    @Override
    public Map<String, Object> onFakeDelete(Map map) {
        return super.onFakeDelete(map);
    }
```

### Expected Behavior/期望结果

```markdown
正常启动
```

### Any additional comments?/其它补充说明？

```markdown
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()"
	at apijson.orm.AbstractSQLConfig.newSQLConfig(AbstractSQLConfig.java:5245)
	at apijson.framework.APIJSONSQLConfig.newSQLConfig(APIJSONSQLConfig.java:232)
	at com.quick.online.parser.OnlineObjectParser.newSQLConfig(OnlineObjectParser.java:34)
	at apijson.orm.AbstractObjectParser.newSQLConfig(AbstractObjectParser.java:834)
	at apijson.orm.AbstractObjectParser.setSQLConfig(AbstractObjectParser.java:856)
	at apijson.orm.AbstractObjectParser.setSQLConfig(AbstractObjectParser.java:38)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1127)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:560)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:278)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:38)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1038)
	at apijson.orm.AbstractParser.onArrayParse(AbstractParser.java:1267)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:540)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:278)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:38)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1038)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:477)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:117)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:403)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:372)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:120)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:52)
	at com.quick.online.util.ApijsonInitUtil.init(ApijsonInitUtil.java:21)
	at com.quick.online.QuickOnlineApplication.main(QuickOnlineApplication.java:51)
2023-12-02 12:13:22.690: 



原因：
查询请求校验规则配置异常 !
java.rmi.ServerException: 查询请求校验规则配置异常 !
	at apijson.framework.APIJSONVerifier.onServerError(APIJSONVerifier.java:582)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:406)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:372)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:120)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:52)
	at com.quick.online.util.ApijsonInitUtil.init(ApijsonInitUtil.java:21)
	at com.quick.online.QuickOnlineApplication.main(QuickOnlineApplication.java:51)
```

**Comment by csx-bill** [comment]
接口请求异常信息
![image](https://github.com/Tencent/APIJSON/assets/31872268/b24fe636-5a8f-4204-a069-0f442463fb0a)
