### ISSUE TITLE
请问现在还支持不导入request,access表吗我按着这里的配置改完之后还是提示不可用 Table 'mysql.access' doesn't exist 

### ISSUE THREAD

**Issue by GeXin97** [Tencent/APIJSON#749]
### Description

然后提交问题，推荐用以下模板修改，注意要换行保持清晰可读。 
【标题】：Table 'mysql.access' doesn't exist 
【内容】： **环境信息**  
 系统: Windows 11 10.0 
 数据库: MYSQL 8.0.11 
 JDK: 17.0.12 amd64 
 APIJSON: 7.0.3

**问题描述**
Table 'mysql.access' doesn't exist 
请问现在还支持不导入request,access表吗我按着这里的配置改完之后还是提示不可用

已按照#12的相关问题修改了
***[DemoVerifier](https://github.com/TommyLemon/APIJSON/blob/b2bd0aac5f6c2bb7e4de2644bd266118b85b06a3/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/demo/server/DemoVerifier.java) 重写 verify 和 verifyLogin 方法，并且都注释掉里面的代码，就不会校验了***
   还是会去access表获取权限

Caused by: java.sql.SQLSyntaxErrorException: Table 'mysql.access' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1004)
	at apijson.orm.AbstractSQLExecutor.executeQuery(AbstractSQLExecutor.java:1393)
	at apijson.orm.SQLExecutor.executeQuery(SQLExecutor.java:70)
	at apijson.orm.AbstractSQLExecutor.execute(AbstractSQLExecutor.java:296)
	at apijson.demo.DemoSQLExecutor.execute(DemoSQLExecutor.java:265)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2051)
	... 22 more
请问有没有类似的demo可以借鉴

**Comment by GeXin97** [comment]
按照demo的操作已实现了基本的功能，但是目前的业务不支持我在数据库新建表，只想使用apijosn的sql生成功能实现一些简单的查询需求， 请问大佬有没有解决方案，小弟万分感谢。

**Comment by GeXin97** [comment]
研究了一下找到了新的校验开关
